version: '2.1'
services:
  ray-caster:
    build:
      context: ./
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "1234:80"
  wasm:
    build:
      context: ./wasm
      dockerfile: wasm.dockerfile
    volumes:
      - ./wasm:/usr/src/app
